### ISSUE TITLE
"Configure clusters" step is quite complicated

### ISSUE THREAD

**Issue by danieleongari** [lsmo-epfl/aiida-lsmo-setup#8]
I see some problems in this step:
* you need to do back and forth between `aiida-lsmo-codes/setup.py` and `aiida-lsmo-setup/computer-configure.yml`
* you need to modify `computer-configure.yml` which will make more complicated to `git pull` when needed
* `look_for_keys: True` is not really working, and you have to enter anyway the path of your key

@ltalirz what do you suggest?
The best solution to me is to remove `computer-configure.yml` and document what they need to write, step by step, in the README. 
Is there any safe more automated option?

**Comment by ltalirz** [comment]
> you need to do back and forth between aiida-lsmo-codes/setup.py and aiida-lsmo-setup/computer-configure.yml

Why? You can finish the setup step first for all computer you need.

**Comment by ltalirz** [comment]
> The best solution to me is to remove computer-configure.yml and document what they need to write, step by step

this is another option

> look_for_keys: True is not really working, and you have to enter anyway the path of your key

ok, we should check what this option actually does - I'm not quite sure.

**Comment by ltalirz** [comment]
fixed in e22173032e2570cbf30c00fcda37fddc58e99bca
