### ISSUE TITLE
point how to run first workflow

### ISSUE THREAD

**Issue by ltalirz** [lsmo-epfl/aiida-lsmo-setup#9]
@danieleongari 
As the final step, could you please add some pointers on how they should run their first workflow?

Details don't need to be in this repo, but at least a link to the instructions (e.g. on aiida-lsmo) would be nice.

**Comment by danieleongari** [comment]
I think this is unrelated to the "setup", and it is however present in our presentation after the setup step: https://docs.google.com/presentation/d/1kUcMAYwAjjKPa-_Vto41rUp5Wp8oWBdK-9QZsN1qNr4/edit#slide=id.g758da4224e_0_165

**Comment by ltalirz** [comment]
Sure, but someone coming to this repo should know where to continue.
One sentence/link can be enough.

**Comment by danieleongari** [comment]
Fair enough, added: https://github.com/lsmo-epfl/aiida-lsmo-setup/commit/1836560afacbbd08b7ee21238d7f921e70809407
